# general config
secrete: "sexx"

blackList:
  - "192.168.1.1"

whiteList:
  #- "127.0.0.2"

# server config
serverConfig:
  frontProjectPath: "C:\\Users\\刘启威\\Desktop\\start_script\\web_resource\\"
  deployFrontProject: false
  managementApiPort: "82"
  adminPort: "81"
  bindIp: "127.0.0.1"



# client config
clientConfig:
  #serverIp: "123.207.114.245"
  serverIp: "127.0.0.1"
  serverPort: "81"
  clientServiceDescriptions:
    - serviceName: "remote desk"
      serviceIp: "192.168.216.131"
      servicePort: "3389"
      serviceEnable: true
    - serviceName: "echo server"
      serviceIp: "127.0.0.1"
      servicePort: "888"
      serviceEnable: true
    - serviceName: "mysql"
      serviceIp: "127.0.0.1"
      servicePort: "3306"
      serviceEnable: true
